export enum Team {
  DEFAULT = "All teams",
  ALAVES = "Deportivo Alaves",
  ATHLETIC = "Athletic Club",
  ATLÉTICO = "Atletico de Madrid",
  BARCELONA = "FC Barcelona",
  BETIS = "Real Betis",
  CELTA = "RC Celta de Vigo",
  GETAFE = "Getafe CF",
  GIRONA = "Girona",
  ESPAÑOL = "RCD Español",
  MALLORCA = "RCD Mallorca",
  OSASUNA = "CA Osasuna",
  RAYO = "Rayo Vallecano",
  REAL_MADRID = "Real Madrid CF",
  REAL_SOCIEDAD = "Real Sociedad",
  SEVILLA = "Sevilla FC",
  VALENCIA = "Valencia CF",
  VILLARREAL = "Villarreal CF",
  REAL_VALLADOLID = "Real Valladolid",
  UD_LAS_PALMAS  = "UD Las Palmas",
  CD_LEGANES = "CD Leganes",
  OTHER = "Other team"
}
