export enum Team {
  ALAVES = "Deportivo Alaves",
  ALMERIA = "UD Almeria",
  ATHLETIC = "Athletic Club",
  ATLÉTICO = "Atletico de Madrid",
  BARCELONA = "FC Barcelona",
  BETIS = "Real Betis",
  CADIZ = "Cadiz CF",
  CELTA = "RC Celta de Vigo",
  Getafe = "Getafe CF",
  GRANADA = "Granada CF",
  LEVANTE = "Levante UD",
  MALLORCA = "RCD Mallorca",
  OSASUNA = "CA Osasuna",
  RAYO = "Rayo Vallecano",
  REAL_MADRID = "Real Madrid CF",
  REAL_SOCIEDAD = "Real Sociedad",
  SEVILLA = "Sevilla FC",
  VALENCIA = "Valencia CF",
  VILLARREAL = "Villarreal CF",
  DEFAULT = "No team"
}
